var TypeScriptModule=function(e){function t(t){for(var n,s,l=t[0],u=t[1],i=t[2],f=0,d=[];f<l.length;f++)s=l[f],Object.prototype.hasOwnProperty.call(o,s)&&o[s]&&d.push(o[s][0]),o[s]=0;for(n in u)Object.prototype.hasOwnProperty.call(u,n)&&(e[n]=u[n]);for(c&&c(t);d.length;)d.shift()();return a.push.apply(a,i||[]),r()}function r(){for(var e,t=0;t<a.length;t++){for(var r=a[t],n=!0,l=1;l<r.length;l++){var u=r[l];0!==o[u]&&(n=!1)}n&&(a.splice(t--,1),e=s(s.s=r[0]))}return e}var n={},o={messageBoxDialog:0},a=[];function s(t){if(n[t])return n[t].exports;var r=n[t]={i:t,l:!1,exports:{}};return e[t].call(r.exports,r,r.exports,s),r.l=!0,r.exports}s.m=e,s.c=n,s.d=function(e,t,r){s.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},s.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},s.t=function(e,t){if(1&t&&(e=s(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(s.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var n in e)s.d(r,n,function(t){return e[t]}.bind(null,n));return r},s.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return s.d(t,"a",t),t},s.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},s.p="";var l=window.webpackJsonpTypeScriptModule=window.webpackJsonpTypeScriptModule||[],u=l.push.bind(l);l.push=t,l=l.slice();for(var i=0;i<l.length;i++)t(l[i]);var c=u;return a.push([1,"vendors-messageBoxDialog"]),r()}({"../../node_modules/webpack/hot sync ^\\.\\/log$":
/*!*************************************************!*\
  !*** (webpack)/hot sync nonrecursive ^\.\/log$ ***!
  \*************************************************/
/*! no static exports found */
/*! all exports used */function(e,t,r){var n={"./log":"../../node_modules/webpack/hot/log.js"};function o(e){var t=a(e);return r(t)}function a(e){if(!r.o(n,e)){var t=new Error("Cannot find module '"+e+"'");throw t.code="MODULE_NOT_FOUND",t}return n[e]}o.keys=function(){return Object.keys(n)},o.resolve=a,e.exports=o,o.id="../../node_modules/webpack/hot sync ^\\.\\/log$"},"./src/View/MessageBox.tsx":
/*!*********************************!*\
  !*** ./src/View/MessageBox.tsx ***!
  \*********************************/
/*! no static exports found */
/*! all exports used */function(e,t,r){"use strict";var n,o=this&&this.__extends||(n=function(e,t){return(n=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,t){e.__proto__=t}||function(e,t){for(var r in t)t.hasOwnProperty(r)&&(e[r]=t[r])})(e,t)},function(e,t){function r(){this.constructor=e}n(e,t),e.prototype=null===t?Object.create(t):(r.prototype=t.prototype,new r)}),a=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};Object.defineProperty(t,"__esModule",{value:!0});var s=a(r(/*! react */"../../node_modules/react/index.js")),l=r(/*! @fluentui/react/lib/Text */"../../node_modules/@fluentui/react/lib/Text.js"),u=r(/*! ../theme/theme */"./src/theme/theme.ts"),i=function(e){function t(t){var r=e.call(this,t)||this;return r.state={},r}return o(t,e),t.prototype.render=function(){var e=u.getThemeForFluent(u.getOfficeTheme()).palette,t=e.black,r=e.white,n=e.neutralDark,o=e.neutralPrimary,a=e.neutralLighter,i=e.neutralTertiary;return s.default.createElement("div",{className:"messagebox-parent",style:{background:n}},s.default.createElement("style",{dangerouslySetInnerHTML:{__html:[".messagebox-editor::-webkit-scrollbar-thumb:hover {","background-color: ",i,"}",".messagebox-editor::-webkit-scrollbar-thumb {","background-color: ",a,"}"].join("\n")}}),s.default.createElement("div",{className:"messagebox-editor",style:{background:r}},s.default.createElement(l.Text,{className:"messagebox-text-code",style:{background:r,color:t}},this.props.message)),s.default.createElement("div",{className:"messagebox-text-footer"},s.default.createElement(l.Text,{className:"messagebox-text-footer",style:{color:o}},this.props.footer)))},t}(s.default.Component);t.default=i},"./src/messageBoxDialog.tsx":
/*!**********************************!*\
  !*** ./src/messageBoxDialog.tsx ***!
  \**********************************/
/*! no static exports found */
/*! all exports used */function(e,t,r){"use strict";var n=this&&this.__createBinding||(Object.create?function(e,t,r,n){void 0===n&&(n=r),Object.defineProperty(e,n,{enumerable:!0,get:function(){return t[r]}})}:function(e,t,r,n){void 0===n&&(n=r),e[n]=t[r]}),o=this&&this.__setModuleDefault||(Object.create?function(e,t){Object.defineProperty(e,"default",{enumerable:!0,value:t})}:function(e,t){e.default=t}),a=this&&this.__importStar||function(e){if(e&&e.__esModule)return e;var t={};if(null!=e)for(var r in e)"default"!==r&&Object.hasOwnProperty.call(e,r)&&n(t,e,r);return o(t,e),t},s=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};Object.defineProperty(t,"__esModule",{value:!0});var l=s(r(/*! ./View/MessageBox */"./src/View/MessageBox.tsx")),u=a(r(/*! ./utils/AppConstants */"./src/utils/AppConstants.ts")),i=r(/*! react-hot-loader */"../../node_modules/react-hot-loader/index.js"),c=s(r(/*! react */"../../node_modules/react/index.js")),f=r(/*! @fluentui/react/lib/Icons */"../../node_modules/@fluentui/react/lib/Icons.js"),d=s(r(/*! react-dom */"../../node_modules/react-dom/index.js"));f.initializeIcons();Office.onReady((function(){!0;var e,t=Office.context.hostSettings.get("Parameters");t&&(e=l.default,console.log(e),d.default.render(c.default.createElement(i.AppContainer,null,c.default.createElement(e,{message:[u.IMPORT_COMMENTS,u.IMPORT_CODE,u.CONFIGURE_COMMENTS,u.CONFIGURE_CODE].join(""),footer:u.FOOTER_1})),document.getElementById("container")))}))},"./src/theme/colors.ts":
/*!*****************************!*\
  !*** ./src/theme/colors.ts ***!
  \*****************************/
/*! no static exports found */
/*! all exports used */function(e,t,r){"use strict";function n(e){switch(e){case"DarkGray":return{neutralPrimary:"#f8f8f8",neutralDark:"#2e2e2e",neutralLighter:"#c2c2c2",neutralTertiary:"#e5e5e5",black:"#ffffff",white:"#4d4d4d"};case"Black":return{neutralPrimary:"#f8f8f8",neutralDark:"#0a0a0a",neutralLighter:"#999999",neutralTertiary:"#d6d6d6",black:"#ffffff",white:"#292929"};case"White":return{neutralPrimary:"#000000",neutralDark:"#f0f0f0",neutralLighter:"#707070",neutralTertiary:"#424242",black:"#000000",white:"#ffffff"};case"Colorful":default:return{neutralPrimary:"#000000",neutralDark:"#f0f0f0",neutralLighter:"#707070",neutralTertiary:"#424242",black:"#000000",white:"#ffffff"}}}Object.defineProperty(t,"__esModule",{value:!0}),t.getSemanticColors=t.getPalette=t.getFluentSVRefreshBackgroundColor=t.getBackgroundColor=void 0,t.getBackgroundColor=function(e){var t;return null!==(t=n(e).white)&&void 0!==t?t:"#ffffff"},t.getFluentSVRefreshBackgroundColor=function(e){switch(e){case"DarkGray":return"#2e2e2e";case"Black":return"#0a0a0a";case"Colorful":case"White":default:return"#f0f0f0"}},t.getPalette=n,t.getSemanticColors=function(e){switch(e){case"Colorful":return{inputBackground:"#ffffff",bodySubtext:"#323130",inputPlaceholderText:"#737373"};case"Black":return{errorText:"#f1707b"};default:return{}}}},"./src/theme/theme.ts":
/*!****************************!*\
  !*** ./src/theme/theme.ts ***!
  \****************************/
/*! no static exports found */
/*! all exports used */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getOfficeTheme=t.loadThemeForFluent=t.getThemeForFluent=void 0;var n=r(/*! @fluentui/react/lib/Styling */"../../node_modules/@fluentui/react/lib/Styling.js"),o=r(/*! ./colors */"./src/theme/colors.ts");function a(e){return n.createTheme({palette:o.getPalette(e),semanticColors:o.getSemanticColors(e)})}t.getThemeForFluent=a,t.loadThemeForFluent=function(e){n.loadTheme(a(e))},t.getOfficeTheme=function(){if(!!!window.Office)return"Colorful";try{var e=Office.context.officeTheme;switch(e?e.bodyBackgroundColor.toUpperCase():""){case"#E6E6E6":return"Colorful";case"#666666":return"DarkGray";case"#262626":return"Black";case"#FFFFFF":return"White";default:return"Colorful"}}catch(e){return"Colorful"}}},"./src/utils/AppConstants.ts":
/*!***********************************!*\
  !*** ./src/utils/AppConstants.ts ***!
  \***********************************/
/*! no static exports found */
/*! all exports used */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.FOOTER_1=t.CONFIGURE_CODE=t.CONFIGURE_COMMENTS=t.IMPORT_CODE=t.IMPORT_COMMENTS=void 0,t.IMPORT_COMMENTS="# The following import statements are pre-loaded.\n\n",t.IMPORT_CODE="import numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport statsmodels as sm\nimport seaborn as sns\nimport excel\n\n\n\n",t.CONFIGURE_COMMENTS="# Set default conversions for the xl() function.\n\n",t.CONFIGURE_CODE="excel.set_xl_scalar_conversion(excel.convert_to_scalar)\n\nexcel.set_xl_array_conversion(excel.convert_to_dataframe)\n\n\n",t.FOOTER_1="Tip: The initialization settings are currently read-only. You can work around this by creating a separate sheet that is the first sheet in your workbook and entering desired import statements and settings on this worksheet. We calculate Python formulas in row-major order and then worksheet order, so code on the first worksheet is the first to run."},1:
/*!******************************************************************************************************************************************!*\
  !*** multi (webpack)-dev-server/client?https://localhost:3000 ./src/messageBoxDialog.tsx office-ui-fabric-react/dist/css/fabric.min.css ***!
  \******************************************************************************************************************************************/
/*! no static exports found */
/*! all exports used */function(e,t,r){r(/*! D:\office\src\sdx\excelinitpyeditor\node_modules\webpack-dev-server\client\index.js?https://localhost:3000 */"../../node_modules/webpack-dev-server/client/index.js?https://localhost:3000"),r(/*! ./src/messageBoxDialog.tsx */"./src/messageBoxDialog.tsx"),e.exports=r(/*! office-ui-fabric-react/dist/css/fabric.min.css */"../../node_modules/office-ui-fabric-react/dist/css/fabric.min.css")}});